MERGE INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, NICKNAME, PROFILE_IMAGE_URL, CREATED_AT, UPDATED_AT)
KEY (EMAIL)
VALUES ('user1',
        'user1@example.com',
        '$2a$10$Sn/UwDHKiiu94YuuTI4.RON6fJYYb2pmKTppRrk8M8tgLuVWb.Ote',
        '화연1',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);


MERGE INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, NICKNAME, PROFILE_IMAGE_URL, CREATED_AT, UPDATED_AT)
KEY (EMAIL)
VALUES ('user2',
        'user2@example.com',
        '$2a$10$Sn/UwDHKiiu94YuuTI4.RON6fJYYb2pmKTppRrk8M8tgLuVWb.Ote',
        '화연2',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);