name: Deploy to Elastic Beanstalk
on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BE/BE
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build jar
        run: ./gradlew bootJar --no-daemon

      - name: Make EB bundle (Procfile + app.jar at root)
        run: |
          mkdir -p bundle
          cp deploy-eb/Procfile bundle/Procfile
          cp build/libs/app.jar bundle/app.jar
          cd bundle && zip -r ../app-${GITHUB_SHA}.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp app-${GITHUB_SHA}.zip s3://${{ secrets.EB_BUCKET }}/be/app-${GITHUB_SHA}.zip

      - name: Create EB application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "build-${{ github.run_number }}" \
            --source-bundle S3Bucket=${{ secrets.EB_BUCKET }},S3Key=be/app-${GITHUB_SHA}.zip

      - name: Deploy to environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "build-${{ github.run_number }}"

      - name: Wait & smoke test
        run: |
          aws elasticbeanstalk wait environment-updated --environment-names "${{ secrets.EB_ENV_NAME }}"
          curl -fsS "http://${{ secrets.PUBLIC_URL }}/swagger-ui/index.html" >/dev/null
